# fly.toml app configuration file generated for counterappangular on 2024-04-30T12:25:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "counterappangular"
build = {
  dockerfile = 'Dockerfile'
 }
  primary_region = "ams"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3_000
  min_machines_running = 0
  processes = [ "app" ]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
